Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('resume.urls')),
]

resume/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name="index"),
    path('CodeProfile', views.codeprofile, name="codeprofile"),
    path('Resume', views.resume, name="resume"),
    path('Contact', views.contact, name="contact"),
    path('Contact-Success', views.contactsuccess, name="contact_success"),
    path('Article', views.article, name="article"),

]

resume/models.py
from django.db import models


def opensourse_img_destination(instance, filename):
    return f'assets/opensource/img/{filename}'


def opensourse_video_destination(instance, filename):
    return f'assets/opensource/videos/{filename}'

def extra_file_destination(instance, filename):
    return f'assets/extra/{filename}'



# Create your models here.

class StaticAssets(models.Model):
    reference_name = models.CharField(null=True, blank=True)
    name = models.CharField(null=True, blank=True)
    value = models.CharField(null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Static Asset"  # Singular form
        verbose_name_plural = "Static Assets"  # Plural form


class OpenSource(models.Model):
    number = models.CharField(null=True, blank=True)
    name = models.CharField(null=True, blank=True)
    description = models.TextField(null=True, blank=True, max_length=200)
    img = models.ImageField(upload_to=opensourse_img_destination, null=True, blank=True)
    video = models.FileField(upload_to=opensourse_video_destination, null=True, blank=True)
    tags = models.CharField(null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    preview = models.URLField(null=True, blank=True)
    published = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Open Source"  # Singular form
        verbose_name_plural = "Open Source"  # Plural form


class Competitive(models.Model):
    name = models.CharField(null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Competitive Programming"  # Singular form
        verbose_name_plural = "Competitive Programming"  # Plural form


class Education(models.Model):
    year = models.CharField(null=True, blank=True)
    name = models.CharField(null=True, blank=True)
    url = models.CharField(null=True, blank=True)
    description = models.TextField(null=True, blank=True, max_length=150)
    grade = models.CharField(null=True, blank=True)
    online = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Education"
        verbose_name_plural = "Education"


class Experience(models.Model):
    year = models.CharField(null=True, blank=True)
    name = models.CharField(null=True, blank=True)
    url = models.CharField(null=True, blank=True)
    description = models.TextField(null=True, blank=True, max_length=150)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Experience"
        verbose_name_plural = "Experiences"


class Skill(models.Model):
    name = models.CharField(null=True, blank=True)
    description = models.CharField(null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Skill"
        verbose_name_plural = "Skills"


class Extra(models.Model):
    reference = models.CharField(null=True, blank=True)
    tag1 = models.CharField(null=True, blank=True)
    tag2 = models.TextField(null=True, blank=True)
    tag3 = models.CharField(null=True, blank=True)
    tag4 = models.IntegerField(null=True, blank=True)
    tag5 = models.BooleanField(null=True, blank=True)
    file = models.FileField(upload_to=extra_file_destination, null=True, blank=True)
    tag6 = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.reference

    class Meta:
        verbose_name = "Extra"
        verbose_name_plural = "Extra"


class ContactUs(models.Model):
    name = models.CharField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(null=True, blank=True)
    message = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Contact Us"
        verbose_name_plural = "Contact Us"

resume/forms.py
from django import forms
from .models import ContactUs
from django.contrib.auth.models import User


class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ['name', 'email', 'phone', 'message']

resume/views.py
import os
from lib2to3.fixes.fix_input import context
from dotenv import load_dotenv
from django.conf import settings
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect, render
from storages.utils import setting
from django.core.mail import send_mail
from .models import StaticAssets, OpenSource, Competitive, Education, Experience, Skill, Extra
from django.views.decorators.cache import cache_page
from .forms import ContactUsForm

load_dotenv()

cache_time = 60 * int(os.getenv('CACHE_TIME'))

# Create your views here.
@cache_page(60 * cache_time)
def index(request):

    profile = get_object_or_404(StaticAssets, reference_name="profile")
    tag1value = get_object_or_404(StaticAssets, reference_name="tag1value")
    tag2value = get_object_or_404(StaticAssets, reference_name="tag2value")
    tag3value = get_object_or_404(StaticAssets, reference_name="tag3value")
    tag4value = get_object_or_404(StaticAssets, reference_name="tag4value")
    profession = get_object_or_404(StaticAssets, reference_name="profession")
    bio = get_object_or_404(StaticAssets, reference_name="index_bio")
    twitter = get_object_or_404(StaticAssets, reference_name="twitter")
    linkedin = get_object_or_404(StaticAssets, reference_name="linkedin")
    github = get_object_or_404(StaticAssets, reference_name="github")
    tag1 = get_object_or_404(StaticAssets, reference_name="tag1")
    tag2 = get_object_or_404(StaticAssets, reference_name="tag2")
    tag3 = get_object_or_404(StaticAssets, reference_name="tag3")
    tag4 = get_object_or_404(StaticAssets, reference_name="tag4")
    resume = get_object_or_404(StaticAssets, reference_name="resume")

    context = {
        "profile": profile,
        "profession": profession,
        "bio": bio,
        "resume": resume,
        "twitter": twitter,
        "linkedin": linkedin,
        "github": github,
        "tag1": tag1,
        "tag2": tag2,
        "tag3": tag3,
        "tag4": tag4,
        "tag1value": tag1value,
        "tag2value": tag2value,
        "tag3value": tag3value,
        "tag4value": tag4value,
    }

    return render(request, "index.html", context=context)

@cache_page(60 * cache_time)
def codeprofile(request):

    open_sources = OpenSource.objects.filter(published=True)
    competitive = Competitive.objects.all().order_by('-id')

    context = {
        "open_sources": open_sources,
        "competitive": competitive,
        "media_url": settings.MEDIA_URL,
    }

    return render(request, "code_profile.html", context=context)

@cache_page(60 * cache_time)
def resume(request):

    educations = Education.objects.all().order_by('-id')
    experiences = Experience.objects.all().order_by('-id')
    skills = Skill.objects.all().order_by('id')
    aboutme = get_object_or_404(Extra, reference="aboutme")

    whyhireme = get_object_or_404(Extra, reference="whyhireme")
    myeducationdesc = get_object_or_404(Extra, reference="myeducationdesc")
    myexperiencedesc = get_object_or_404(Extra, reference="myexperiencedesc")
    myskillsdesc = get_object_or_404(Extra, reference="myskillsdesc")
    aboutmedesc = get_object_or_404(Extra, reference="aboutmedesc")

    context = {
        "educations": educations,
        "experiences": experiences,
        "skills": skills,
        "aboutme": aboutme,
        "whyhireme": whyhireme,
        "myeducationdesc": myeducationdesc,
        "myexperiencedesc": myexperiencedesc,
        "myskillsdesc": myskillsdesc,
        "aboutmedesc": aboutmedesc,
    }

    return render(request, "resume.html", context=context)

@cache_page(60 * cache_time)
def contactsuccess(request):
    return render(request, "contact_success.html")


@cache_page(60 * cache_time)
def contact(request):
    if request.method == "POST":
        form = ContactUsForm(request.POST)
        if form.is_valid():
            form.save()

            message_content = form.cleaned_data.get('message')
            sender = form.cleaned_data.get('email')
            send_mail(
                subject = "New Message Form Portfolio",
                message = f"""
                                A Message Has been sent By: {sender}
                                
                                {message_content}
    
                            """,
                from_email = settings.DEFAULT_FROM_EMAIL,
                recipient_list = [settings.ADMIN_EMAIL1, settings.ADMIN_EMAIL2],
                fail_silently = True,
            )

            return redirect('contact_success')

    email1 = get_object_or_404(StaticAssets, reference_name="email1")
    email2 = get_object_or_404(StaticAssets, reference_name="email2")
    linkedin = get_object_or_404(StaticAssets, reference_name="linkedin")
    twitter = get_object_or_404(StaticAssets, reference_name="twitter")

    context = {
        "email1": email1,
        "email2": email2,
        "linkdin": linkedin,
        "twitter": twitter,
    }

    return render(request, "contact.html", context=context)


@cache_page(60 * cache_time)
def article(request):
    return render(request, "articles.html")

resume/templates/articles.html
{% extends 'base.html' %}

{% block content %}

    <main class="mt-24 mx-8 sm:mt-10 sm:mx-8 md:mx-16 md:mt-24 lg:mx-20 lg:mt-24">
        <div id="contact-form" class="flex items-center justify-center py-8 px-4 lg:px-0">
            <!-- Form Section -->
            <div class="max-w-md w-full p-8 bg-neutral-900/75 rounded-lg shadow-lg">
                <!-- Title Section -->
                <h2 class="text-green-400 text-3xl font-bold text-center">Comming Soon</h2>

                <a href="{% url 'index' %}"
                    class="mt-6 block w-full text-center p-3 bg-green-400 text-black font-semibold rounded-lg hover:bg-green-500 transition duration-300 ease-in-out shadow-lg">
                    Go Back
                </a>
            </div>
        </div>


    </main>

{% endblock %}

resume/templates/base.html
{% include 'header.html' %}

{% block content %}

{% endblock %}

{% include 'footer.html' %}

resume/templates/code_profile.html
{% extends 'base.html' %}

{% block content %}
<main class="mt-24 mx-8 sm:mt-10 sm:mx-8 md:mx-16 md:mt-28 lg:mx-20 lg:mt-24">
        <div id="compitative-platforms">
            <h1 class="text-center text-5xl underline" style="font-family: 'Caveat', cursive;">
                Compitative Platforms
            </h1>
            <div class="mt-14 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
                {% for profile in competitive %}
                    <div class="text-white p-8 rounded-lg shadow-lg border border-green-500 max-w-sm mx-auto">
                    <h2
                        class="text-2xl font-bold mb-4 text-center text-green-400 flex items-center justify-center space-x-2">
                        <span>{{ profile.name }}</span>
                        <a href="{{ profile.url }}" target="_blank"
                            class="text-green-400 hover:text-green-400">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-box-arrow-up-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                    d="M8.636 3.5a.5.5 0 0 0-.5-.5H1.5A1.5 1.5 0 0 0 0 4.5v10A1.5 1.5 0 0 0 1.5 16h10a1.5 1.5 0 0 0 1.5-1.5V7.864a.5.5 0 0 0-1 0V14.5a.5.5 0 0 1-.5.5h-10a.5.5 0 0 1-.5-.5v-10a.5.5 0 0 1 .5-.5h6.636a.5.5 0 0 0 .5-.5" />
                                <path fill-rule="evenodd"
                                    d="M16 .5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h3.793L6.146 9.146a.5.5 0 1 0 .708.708L15 1.707V5.5a.5.5 0 0 0 1 0z" />
                            </svg>
                        </a>
                    </h2>
                    {{ profile.description | safe }}
                </div>
                {% endfor %}
            </div>
        </div>

        <div id="Open-source" class="mt-20 lg:mt-28">
            <h1 class="text-center text-5xl underline" style="font-family: 'Caveat', cursive;">
                Open Source Projects
            </h1>


            <div id="default-carousel" class="relative  mt-20 md:mx-10" data-carousel="static">
                <!-- Carousel wrapper -->
                <div class="relative overflow-hidden rounded-lg h-[25rem] md:h-[25rem] lg:h-96">
                    {% for open_source in open_sources %}
                    <div class="flex duration-700 ease-in-out" data-carousel-item>
                        <div class="md:w-1/2">
                            <div>
                                <p class="text-6xl" style="font-family: 'Chakra Petch', sans-serif">{{ open_source.number }}</p>
                                <p class="mt-6 text-3xl font-semibold">{{ open_source.name }}</p>
                                <p class="mt-3">{{ open_source.description }}</p>
                                <p class="mt-4 text-green-400 font-bold">{{ open_source.tags }}</p>
                                <div class="border-t border-gray-600 my-4 mr-6"></div>
                                <div class="mt-4 flex space-x-4">
                                    {% if open_source.preview %}
                                        <a target="_blank" href="{{ open_source.preview }}" class="p-2 bg-gray-700 rounded-full hover:bg-green-400">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                fill="currentColor" class="bi bi-arrow-up-right" viewBox="0 0 16 16">
                                                <path fill-rule="evenodd"
                                                    d="M14 2.5a.5.5 0 0 0-.5-.5h-6a.5.5 0 0 0 0 1h4.793L2.146 13.146a.5.5 0 0 0 .708.708L13 3.707V8.5a.5.5 0 0 0 1 0z" />
                                            </svg>
                                        </a>
                                    {% else %}
                                        <a target="_blank" href="{{ media_url }}{{ open_source.video }}" class="p-2 bg-gray-700 rounded-full hover:bg-green-400">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                fill="currentColor" class="bi bi-arrow-up-right" viewBox="0 0 16 16">
                                                <path fill-rule="evenodd"
                                                    d="M14 2.5a.5.5 0 0 0-.5-.5h-6a.5.5 0 0 0 0 1h4.793L2.146 13.146a.5.5 0 0 0 .708.708L13 3.707V8.5a.5.5 0 0 0 1 0z" />
                                            </svg>
                                        </a>
                                    {% endif %}
                                    <a target="_blank" href="{{ open_source.url }}" class="p-2 bg-gray-700 rounded-full hover:bg-green-400">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                            fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                                            <path
                                                d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8" />
                                        </svg>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="hidden md:block md:w-1/2 ">
                            <img class="h-4/5 w-full lg:h-full lg:w-full rounded-lg" src="{{ media_url }}{{ open_source.img }}" alt="">
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <div class="text-center space-x-4 pb-4 md:mt-10">
                    <button class="p-2  bg-green-400 hover:bg-green-600 focus:outline-none" data-carousel-prev>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"
                            class="w-6 h-6 text-black">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
                        </svg>
                        <span class="sr-only">Previous</span>
                    </button>
                    <button class="p-2  bg-green-400 hover:bg-green-600 focus:outline-none" data-carousel-next>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"
                            class="w-6 h-6 text-black">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                        </svg>
                        <span class="sr-only">Next</span>
                    </button>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

resume/templates/contact.html
{% extends 'base.html' %}

{% block content %}

<main class="mt-24 mx-8 sm:mt-10 sm:mx-8 md:mx-16 md:mt-24 lg:mx-20 lg:mt-24">
        <div id="contact-form" class="flex flex-col lg:flex-row">
            <!-- Form Section -->

                <div class="w-full lg:w-1/2 p-8 bg-neutral-900/75 rounded-lg shadow-lg">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p class="text-green-400 text-3xl font-bold">Let's Work Together</p>
                        <p class="text-gray-300 text-sm mt-4 leading-relaxed">
                            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
                            industry's standard dummy text ever since the 1500s.
                        </p>

                        <!-- Name Input -->
                        <div class="input-section mt-8">
                            <label for="name" class="text-gray-400 text-sm">Name</label>
                            <input
                                class="w-full mt-2 p-3 bg-stone-950 text-gray-200 border border-green-400 rounded-lg focus:ring-2 focus:ring-green-400 focus:outline-none shadow-md"
                                value="{{ name }}" type="text" name="name" id="id_name" placeholder="Enter your name" aria-label="Enter your name" required>
                        </div>

                        <!-- Email Input -->
                        <div class="input-section mt-6">
                            <label for="email" class="text-gray-400 text-sm">Email</label>
                            <input
                                class="w-full mt-2 p-3 bg-stone-950 text-gray-200 border border-green-400 rounded-lg focus:ring-2 focus:ring-green-400 focus:outline-none shadow-md"
                                value="{{ email }}" type="email" name="email" id="id_email" placeholder="Enter your email" required
                                aria-label="Enter your email">
                        </div>

                        <!-- Phone Number Input -->
                        <div class="input-section mt-6">
                            <label for="phone" class="text-gray-400 text-sm">Phone Number</label>
                            <input
                                class="w-full mt-2 p-3 bg-stone-950 text-gray-200 border border-green-400 rounded-lg focus:ring-2 focus:ring-green-400 focus:outline-none shadow-md"
                                value="{{ phone }}" type="tel" name="phone" id="id_phone" placeholder="Enter your phone number"
                                aria-label="Enter your phone number">
                        </div>

                        <!-- Message Textarea -->
                        <div class="input-section mt-6">
                            <label for="message" class="text-gray-400 text-sm">Message</label>
                            <textarea
                                class="w-full mt-2 p-3 bg-stone-950 text-gray-200 border border-green-400 rounded-lg focus:ring-2 focus:ring-green-400 focus:outline-none shadow-md"
                                value="{{ message }}" name="message" id="id_message" rows="5" placeholder="Enter your message" required
                                aria-label="Enter your message"></textarea>
                        </div>

                        <!-- Submit Button -->
                        <button name="submit-feedback" type="submit"
                            class="mt-6 w-full p-3 bg-green-400 text-black font-semibold rounded-lg hover:bg-green-500 transition duration-300 ease-in-out shadow-lg">
                            Send Message
                        </button>
                    </form>
                </div>


            <!-- Contact Info Section -->
            <div class="w-full lg:w-1/2 mt-10 lg:mt-0 lg:ml-10">
                <div
                    class="flex flex-col items-start justify-center p-8 bg-neutral-900/75 rounded-lg shadow-lg text-gray-300 space-y-6">
                    <!-- Email Section -->
                    <div class="flex items-center space-x-4">
                        <div class="p-3 bg-stone-950 rounded-full">
                            <svg class="w-6 h-6 text-green-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"
                                fill="currentColor">
                                <path
                                    d="M2.999 3c0-.551.449-1 1-1h16c.552 0 1 .449 1 1v18c0 .551-.448 1-1 1H3.999c-.552 0-1-.449-1-1V3zm9 10.5c-.055.018-.11.038-.167.038H11.165c-.055 0-.11-.02-.167-.038l-8-4c-.033-.015-.063-.035-.096-.052v10.552h16V9.448c-.034.017-.064.037-.097.052l-8 4zm7.5-5.448L12.501 11.7 4.499 8.052V5h14v2.052z" />
                            </svg>
                        </div>
                        <div>
                            <p class="text-sm">Primary Email</p>
                            <p class="text-lg font-semibold">{{ email1.value }}</p>
                        </div>
                    </div>

                    <!-- Secondary Email Section -->
                    <div class="flex items-center space-x-4">
                        <div class="p-3 bg-stone-950 rounded-full">
                            <svg class="w-6 h-6 text-green-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"
                                fill="currentColor">
                                <path
                                    d="M2.999 3c0-.551.449-1 1-1h16c.552 0 1 .449 1 1v18c0 .551-.448 1-1 1H3.999c-.552 0-1-.449-1-1V3zm9 10.5c-.055.018-.11.038-.167.038H11.165c-.055 0-.11-.02-.167-.038l-8-4c-.033-.015-.063-.035-.096-.052v10.552h16V9.448c-.034.017-.064.037-.097.052l-8 4zm7.5-5.448L12.501 11.7 4.499 8.052V5h14v2.052z" />
                            </svg>
                        </div>
                        <div>
                            <p class="text-sm">Secondary Email</p>
                            <p class="text-lg font-semibold">{{ email2.value }}</p>
                        </div>
                    </div>

                    <!-- Twitter Section -->
                    <div class="flex items-center space-x-4">
                        <div class="p-3 bg-stone-950 rounded-full">
                            <svg class="w-6 h-6 text-blue-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"
                                fill="currentColor">
                                <path
                                    d="M24 4.557a9.94 9.94 0 01-2.828.775 4.937 4.937 0 002.165-2.723c-.951.563-2.005.974-3.127 1.195a4.92 4.92 0 00-8.384 4.482 13.963 13.963 0 01-10.141-5.15 4.822 4.822 0 00-.666 2.475 4.92 4.92 0 002.19 4.107 4.903 4.903 0 01-2.228-.616v.061a4.926 4.926 0 003.946 4.827 4.902 4.902 0 01-2.224.084 4.926 4.926 0 004.602 3.417A9.869 9.869 0 010 21.54a13.945 13.945 0 007.548 2.212c9.142 0 14.307-7.721 14.307-14.426 0-.22-.005-.44-.015-.659A10.257 10.257 0 0024 4.557z" />
                            </svg>
                        </div>
                        <div>
                            <p class="text-sm">Twitter</p>
                            <p class="text-lg font-semibold"><a target="_blank"
                                    href="{{ twitter.value }}"
                                    class="text-blue-400">twitter.com/everydaycodings</a></p>
                        </div>
                    </div>

                    <!-- LinkedIn Section -->
                    <div class="flex items-center space-x-4">
                        <div class="p-3 bg-stone-950 rounded-full">
                            <svg class="w-6 h-6 text-blue-600" xmlns="http://www.w3.org/2000/svg" fill="currentColor"
                                viewBox="0 0 24 24">
                                <path
                                    d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.761 0 5-2.239 5-5v-14c0-2.761-2.239-5-5-5zm-11.579 20h-3.421v-10h3.421v10zm-1.711-11.309c-1.098 0-1.989-.891-1.989-1.992 0-1.102.89-1.992 1.989-1.992s1.989.89 1.989 1.992c0 1.102-.89 1.992-1.989 1.992zm13.29 11.309h-3.421v-5.622c0-1.336-.026-3.054-1.862-3.054-1.862 0-2.148 1.454-2.148 2.957v5.719h-3.421v-10h3.283v1.364h.047c.457-.864 1.576-1.774 3.243-1.774 3.466 0 4.107 2.28 4.107 5.242v5.168z" />
                            </svg>
                        </div>
                        <div>
                            <p class="text-sm">LinkedIn</p>
                            <p class="text-lg font-semibold"><a target="_blank"
                                    href="{{ linkdin.value }}"
                                    class="text-blue-600">linkedin.com/in/kumarsaksham1891</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock %}

resume/templates/contact_success.html
{% extends 'base.html' %}

{% block content %}

    <main class="mt-24 mx-8 sm:mt-10 sm:mx-8 md:mx-16 md:mt-24 lg:mx-20 lg:mt-24">
        <div id="contact-form" class="flex items-center justify-center py-8 px-4 lg:px-0">
            <!-- Form Section -->
            <div class="max-w-md w-full p-8 bg-neutral-900/75 rounded-lg shadow-lg">
                <!-- Title Section -->
                <h2 class="text-green-400 text-2xl font-bold">Message Sent Successfully</h2>
                <p class="text-gray-300 text-sm mt-4 leading-relaxed">
                    Your message has been successfully sent to EverydayCodings. Please be patient, and I will contact you soon.
                </p>
                <a href="{% url 'contact' %}"
                    class="mt-6 block w-full text-center p-3 bg-green-400 text-black font-semibold rounded-lg hover:bg-green-500 transition duration-300 ease-in-out shadow-lg">
                    Go Back
                </a>
            </div>
        </div>


    </main>

{% endblock %}

resume/templates/footer.html
<footer class="bg-gradient-to-r from-neutral-900 to-gray-800 text-gray-400 py-6 shadow-lg mt-40">
    <div class="container mx-auto px-4 flex flex-col md:flex-row justify-between items-center">
        <!-- Open Source Message and Source Code Link -->
        <div class="mt-4 md:mt-0 text-center md:text-left w-full md:w-1/2">
            <p class="text-sm text-gray-400">
                This project is <span class="text-green-400 font-semibold">Open Source</span> and available on
                <a href="{{ source_code }}" class="text-blue-400 font-semibold hover:underline" target="_blank" rel="noopener noreferrer">
                    GitHub
                </a>
            </p>
        </div>

        <!-- Last Updated Date -->
        <div class="mt-4 md:mt-0 text-center md:text-right w-full md:w-1/2">
            <p class="text-sm text-gray-300">
                Last updated: <span class="font-semibold">{{ last_updated }}</span>
            </p>
        </div>
    </div>
</footer>



</body>
<script>
    // JavaScript function to show content based on the clicked tab
    function showTabContent(tabId) {
        // Hide all tab content
        var contents = document.querySelectorAll('.tab-content');
        contents.forEach(content => {
            content.classList.add('hidden');
        });

        // Show the selected tab content
        document.getElementById(tabId).classList.remove('hidden');
    }
</script>
<script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.1/dist/flowbite.min.js"></script>

</html>